version: '3'

services:
  grpc-server:
    build:
      context: ../
      dockerfile: docker/server.Dockerfile
    image: grpcplanningpoker.azurecr.io/machimachida/grpc-planning-poker:2.1
    container_name: grpc-planning-poker-server
    ports:
      - 8080:8080
